contact_links:
    - name: Questions
      about: If you are new to xrdp and want to ask something, raise it as Q&A in discussion.
      url: https://github.com/neutrinolabs/xrdp/discussions/new?category=q-a

